#!/bin/csh -fx

# Run the Speciation Tool
# Perl input arguements:
# 	SPTOOL_DB - Postgres database name
# 	Scenario Name
# 	Run control file

set TODAY = `date +%Y%b%d`
#set OUTDIR = /disk43/sptool/wa4_02.2016/outputs
set OUTDIR = /sol/work/EMIS/tools/sptool/sptoolv4_0/EPA_outputs
#
mkdir -p $OUTDIR

echo " "
echo "==================================================================================="
printf "              CMAQ CB6 criteria"
date

cat > RUNCTL << IEOF
mech_basis,CB6
run_type,CRITERIA
AQM,CMAQ
output,VOC
splits_out,$OUTDIR/gspro.CB6_criteria.CMAQ.$TODAY.txt
cnv_out,$OUTDIR/gscnv.CB6_criteria.CMAQ.$TODAY.txt
IEOF

perl $SPTOOL_SRC_HOME/run_sptool.pl $SPTOOL_DB cmaq_cb6_criteria RUNCTL >& log.CMAQ.CB6_criteria.$TODAY
date

