#

# Run the Speciation Tool
# Perl input arguements:
# 	SPTOOL_DB - Postgres database name
# 	Scenario Name
# 	Run control file

set TODAY = `date +%Y%b%d`
#set OUTDIR = /disk43/sptool/wa4_02.2016/outputs
set OUTDIR = /sol/work/EMIS/tools/sptool/sptoolv4_0/outputs
#
mkdir -p $OUTDIR

echo " "
echo "==================================================================================="
printf "              SAPRC07T criteria "
date

cat > RUNCTL << IEOF
mech_basis,SAPRC07T
run_type,CRITERIA
AQM,CMAQ
output,VOC
splits_out,$OUTDIR/gspro.SAPRC07T_criteria.CMAQ.$TODAY.txt
cnv_out,$OUTDIR/gscnv.SAPRC07T_criteria.CMAQ.$TODAY.txt
IEOF

perl $SPTOOL_SRC_HOME/run_sptool.pl $SPTOOL_DB SAPRC07T_criteria RUNCTL >& log.SAPRC07T_criteria.$TODAY
date



