#!/bin/sh
#
#   Startup/shutdown script for apache tomcat
#
#   Linux chkconfig stuff:
#   chkconfig: 2345 98 02
#   description: Startup/shutdown script for apache tomcat
#
#
#  Created by Alexis Zubrow

## Environmental Variables
prog=tomcat
CATALINA_HOME=/usr/local/apache-tomcat  ## tomcat top dir
export JAVA_HOME=/usr/local/java/jre1.6.0_01/  ## Java top dir
TOMCAT_USER=emf  ## run tomcat as user

## --------------------------------------------------------------##
## want to run as specific user, also need to directly set JAVA_HOME for 
## this login
start () {
	echo -n $"Starting $prog: "
	su - $TOMCAT_USER -s /bin/bash -c "export JAVA_HOME=$JAVA_HOME;$CATALINA_HOME/bin/startup.sh"
}

stop () {
	echo -n $"Stopping $prog: "
	su - $TOMCAT_USER -s /bin/bash -c "export JAVA_HOME=$JAVA_HOME; $CATALINA_HOME/bin/shutdown.sh"
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	
        *)
	echo $"Usage: $prog {start|stop|restart}"
	exit 1
esac

##exit $RETVAL
