#!/bin/csh -fx
#

# Run the Speciation Tool
# Perl input arguements:
# 	SPTOOL_DB - Postgres database name
# 	Scenario Name
# 	Run control file

set TODAY = `date +%Y%b%d`
#set OUTDIR = /disk43/sptool/wa4_02.2016/outputs
set OUTDIR = /sol/work/EMIS/tools/sptool/sptoolv4_0/CB6CMAQ_NATA/out
#
mkdir -p $OUTDIR


echo " "
echo "==================================================================================="
printf "              CB6CMAQ nointegrate "
date

cat > RUNCTL << IEOF
mech_basis,CB6CMAQ
run_type,NOINTEGRATE
AQM,CMAQ
output,VOC
tox_file,/sol/work/EMIS/tools/sptool/sptoolv4_0/CB6CMAQ_NATA/tbl_tox_NBAFM_11oct2016_v6.csv
splits_out,$OUTDIR/gspro.CB6CMAQ_nointegrate.CMAQ.$TODAY.txt
cnv_out,$OUTDIR/gscnv.CB6CMAQ_nointegrate.CMAQ.$TODAY.txt
IEOF

setenv SPTOOL_USER sptool

perl $SPTOOL_SRC_HOME/run_sptool.pl $SPTOOL_DB cb6cmaq_test RUNCTL 
#>& log.CB6CMAQ_nointegrate.$TODAY
date



